# frozen_string_literal: true

source "http://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "2.5.1"

gem "rails", "~> 5.2.1"
gem "pg", ">= 0.18", "< 2.0"
gem "puma", "~> 3.11"
gem "bcrypt", "~> 3.1.7"
gem "doorkeeper"
gem "bootsnap", ">= 1.1.0", require: false
gem "rack-cors", require: "rack/cors"
gem "carrierwave", "~> 1.0"
gem "mini_magick"
gem "jbuilder", "~> 2.7.0"
gem "twitter", "~> 6.2.0"
gem "oauth", "~> 0.5.4"
gem "awesome_print"
gem 'httparty', '~> 0.13.7'

group :development, :test do
  gem "faker"
  gem "factory_bot_rails"
  gem "byebug", platforms: [:mri, :mingw, :x64_mingw]
  gem "rspec-rails", "~> 3.8"
  gem "rubocop-rails_config"
  gem "dotenv-rails"
end

group :development do
  gem "listen", ">= 3.0.5", "< 3.2"
  gem "spring"
  gem "spring-watcher-listen", "~> 2.0.0"
end

group :test do
  gem "shoulda-matchers"
  gem "database_cleaner"
end

gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]
